<?php

namespace Alphavel\Alpha;

/**
 * Package Manifest
 * 
 * Reads vendor/composer/installed.json and builds a cache
 * of Alphavel packages with their providers
 */
class PackageManifest
{
    private string $basePath;
    
    private string $vendorPath;
    
    private string $manifestPath;

    public function __construct(string $basePath)
    {
        $this->basePath = $basePath;
        $this->vendorPath = $basePath . '/vendor';
        $this->manifestPath = $basePath . '/bootstrap/cache/packages.php';
    }

    /**
     * Get the current package manifest
     */
    public function getManifest(): array
    {
        if (!$this->manifestExists()) {
            $this->build();
        }

        return require $this->manifestPath;
    }

    /**
     * Build the package manifest and cache it
     */
    public function build(): array
    {
        $packages = [];

        // Read composer's installed.json
        $installed = $this->getInstalledPackages();

        foreach ($installed as $package) {
            // Check if package has alphavel configuration
            if (isset($package['extra']['alphavel'])) {
                $config = $package['extra']['alphavel'];
                
                $packages[$package['name']] = [
                    'name' => $package['name'],
                    'version' => $package['version'] ?? 'dev',
                    'providers' => $config['providers'] ?? [],
                    'aliases' => $config['aliases'] ?? [],
                    'config' => $config['config'] ?? [],
                    'migrations' => $config['migrations'] ?? null,
                    'routes' => $config['routes'] ?? null,
                    'views' => $config['views'] ?? null,
                    'commands' => $config['commands'] ?? [],
                ];
            }
        }

        $this->write($packages);

        return $packages;
    }

    /**
     * Check if manifest file exists
     */
    public function manifestExists(): bool
    {
        return file_exists($this->manifestPath);
    }

    /**
     * Delete the manifest file
     */
    public function delete(): void
    {
        if ($this->manifestExists()) {
            unlink($this->manifestPath);
        }
    }

    /**
     * Get installed packages from composer
     */
    private function getInstalledPackages(): array
    {
        $installedPath = $this->vendorPath . '/composer/installed.json';

        if (!file_exists($installedPath)) {
            return [];
        }

        $content = file_get_contents($installedPath);
        $data = json_decode($content, true);

        // Composer 2.x format
        if (isset($data['packages'])) {
            return $data['packages'];
        }

        // Composer 1.x format (fallback)
        return $data ?? [];
    }

    /**
     * Write the manifest to cache file
     */
    private function write(array $packages): void
    {
        $cacheDir = dirname($this->manifestPath);

        if (!is_dir($cacheDir)) {
            mkdir($cacheDir, 0755, true);
        }

        $content = "<?php\n\n";
        $content .= "// This file is auto-generated by Alpha CLI\n";
        $content .= "// Do not edit manually\n\n";
        $content .= "return " . var_export($packages, true) . ";\n";

        file_put_contents($this->manifestPath, $content);
    }

    /**
     * Get providers from all packages
     */
    public function getProviders(): array
    {
        $manifest = $this->getManifest();
        $providers = [];

        foreach ($manifest as $package) {
            $providers = array_merge($providers, $package['providers']);
        }

        return array_unique($providers);
    }

    /**
     * Get aliases from all packages
     */
    public function getAliases(): array
    {
        $manifest = $this->getManifest();
        $aliases = [];

        foreach ($manifest as $package) {
            $aliases = array_merge($aliases, $package['aliases']);
        }

        return $aliases;
    }

    /**
     * Get commands from all packages
     */
    public function getCommands(): array
    {
        $manifest = $this->getManifest();
        $commands = [];

        foreach ($manifest as $package) {
            $commands = array_merge($commands, $package['commands']);
        }

        return array_unique($commands);
    }

    /**
     * Get package configuration
     */
    public function getPackage(string $name): ?array
    {
        $manifest = $this->getManifest();

        return $manifest[$name] ?? null;
    }

    /**
     * Check if package is installed
     */
    public function hasPackage(string $name): bool
    {
        $manifest = $this->getManifest();

        return isset($manifest[$name]);
    }

    /**
     * Get all package names
     */
    public function getPackageNames(): array
    {
        $manifest = $this->getManifest();

        return array_keys($manifest);
    }
}
